## This is a dummy file and can be used to add cluster role binding for a cluster role to given groups,
## The binding is added to groups mentioned with group object id.
## The binding is added on given role.
## This way users from given groups can be given permissions to cluster.
## If not needed file can be deleted or used with dynamic values.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-admins-group
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group-object-id1
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: group-object-id2
