apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-tuner
  namespace: kube-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-tuner
  namespace: kube-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - tune-privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-tuner
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: node-tuner
roleRef:
  kind: Role
  name: node-tuner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tune-privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: dynamic-tuner-__nodepool__
spec:
  selector:
    matchLabels:
      app: dynamic-tuner-__nodepool__
  template:
    metadata:
      labels:
        app: dynamic-tuner-__nodepool__
    spec:
      hostPID: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      initContainers:
      - name: tune-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sh", "-c"]
        args:
        - |-
          sysctl -w vm.max_map_count=262144
      containers:
      - name: print-hello
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c", "while true; do sleep 3600; done;" ]
      tolerations: __tolerations__
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - __nodepool__
      nodeSelector:
        cambridgesemantics.com/node-purpose: dynamic
      serviceAccountName: node-tuner
