---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: dynamic-tuner-__nodepool__
spec:
  selector:
    matchLabels:
      app: dynamic-tuner-__nodepool__
  template:
    metadata:
      labels:
        app: dynamic-tuner-__nodepool__
    spec:
      hostPID: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      initContainers:
      - name: tune-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sh", "-c"]
        args:
        - |-
          sysctl -w vm.max_map_count=262144
      containers:
      - name: print-hello
        image: busybox
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c", "while true; do sleep 3600; done;" ]
      tolerations: __tolerations__
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - __nodepool__
      nodeSelector:
        cambridgesemantics.com/node-purpose: dynamic
      serviceAccountName: node-tuner
